services:
  - type: web
    name: meetup-scheduler
    env: node
    buildCommand: >
      npm install && 
      npm install typescript @types/react @types/node @types/react-dom && 
      npx prisma generate && 
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://meetup-scheduler.onrender.com 